Solucion del ejercicio 1 al 19 - Sawczuk
PYLP-UNaM/PYLP pull request #372
Opened 2020-12-01 12:08 UTC by NicoSawczuk

solved #371 (TP 4 Haskell - Sawczuk)

2020-12-01 17:33 UTC, martinnacimiento requested changes
El nombre el archivo debería cambiarse a `funciones_sawczuk.hs`  debido a que el archivo proporcionado por la cátedra era de ejemplo como en todos los otros trabajos, y ademas para evitar pisar el mismo archivo con los PR en caso que otra persona hiciera lo mismo.

2020-12-01 18:01 UTC, martinnacimiento reviewed
# Code review 🧐

- Test de ejecución 
  - [x] Exitoso ✅
  - [ ] No esperado ❌
- Legibilidad del código
  - [x] Excelente 😄
  - [ ] Regular 🤔
  - [ ] No se entiende 😵‍💫

## Notas

- EJERCICIO 11: si bien esta el operador potencia esta en el lenguaje, la idea era aplicar el ejercicio con recursividad para armar tu propia función que simula este operador sin hacer uso del mismo. Ademas no haría falta poner Double como valor que devuelve la función, sino Integer, en caso de que lo hagas recursivo.

2020-12-08 20:03 UTC, SuichiM commented
@NicoSawczuk lo que paso ahora al renombrar el archivo original, es que marca que eliminaste el mismo. funciones.hs deberias dejarlo con el contenido original que tenia:

```
module Funciones where

{- Funciones iniciales -}

-- 1. sucesor
sucesor :: Integer -> Integer
sucesor x = x + 1

pre :: Integer -> Integer
pre x = x - 1 

-- 2. doble 
doble :: Integer -> Integer
doble x = x+x
```

2020-12-08 21:31 UTC, NicoSawczuk commented
> @NicoSawczuk lo que paso ahora al renombrar el archivo original, es que marca que eliminaste el mismo. funciones.hs deberias dejarlo con el contenido original que tenia:
> 
> ```
> module Funciones where
> 
> {- Funciones iniciales -}
> 
> -- 1. sucesor
> sucesor :: Integer -> Integer
> sucesor x = x + 1
> 
> pre :: Integer -> Integer
> pre x = x - 1 
> 
> -- 2. doble 
> doble :: Integer -> Integer
> doble x = x+x
> ```

2020-12-08 21:46 UTC, SuichiM commented
@NicoSawczuk  no cierres el PR, manejemoslo aca, hace un pull, primero. capaz que porque el nombre del archivo lo modificaste directamente aca en github y eso hizo un comiit que vos no tenes en tu local. 

hace pull primero y luego commit y push.

2020-12-08 21:56 UTC, NicoSawczuk commented
Creo que es ese problema que usted dice, pero ya intenté hacer pull, fue exitoso e igual el problema persiste

2020-12-08 22:01 UTC, SuichiM commented
Asegurate estar en el mismo branch de este issue y proba hacer `git pull
origin <branch_name>`

Hace un git log para verificar que el commit este en la lista

El mar., 8 dic. 2020 18:56, Nicolás Sawczuk <notifications@github.com>
escribió:

> Creo que es ese problema que usted dice, pero ya intenté hacer pull, fue
> exitoso e igual el problema persiste
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/PYLP-UNaM/PYLP/pull/372#issuecomment-741096506>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFAYZ5VE7TBJ4XNGKI3NOZTST2OIHANCNFSM4UI6AQTA>
> .
>

2020-12-11 20:15 UTC, SuichiM commented
chaque esta complicado ese merge! jaja! se rompio todito! ahi arregle @NicoSawczuk, si queres pegarle una revisada! jaja

2020-12-11 20:25 UTC, SuichiM commented
ahora si! 
![](https://www.reactiongifs.com/r/mgc.gif)

2020-12-11 20:25 UTC, merged

2020-12-11 22:37 UTC, NicoSawczuk commented
Que se rompió profe? Pensé que lo había solucionado 😐🤣

2020-12-11 23:06 UTC, SuichiM commented
fiajate en este commit como habia quedado, tu archivo de funciones 

https://github.com/PYLP-UNaM/PYLP/pull/372/commits/ba0c4f3bcae421be259e3f7e0e1f07251914b6d5

habian quedado algunos conflictos sin resolver, igual removi eso y quedo todo joya!