solución Ejercicio 2 - Lacheski
PYLP-UNaM/PYLP pull request #655
Opened 2022-09-22 15:09 UTC by martinlacheski

fixes issue #623

2022-09-24 18:09 UTC, jorferr89 approved these changes

2022-09-25 19:58 UTC, matiasagbenitez approved these changes

2022-09-26 13:14 UTC, matiasagbenitez requested changes
Según entiendo, no hay procesos que se ejecuten concurrentemente, sino un solo proceso que se ejecuta 100 veces. Revisar

2022-09-26 15:08 UTC, matiasagbenitez approved these changes
Correcta la modificación! Aprobado.

2022-09-26 16:40 UTC, martinfeldman approved these changes

2022-09-27 20:19 UTC, merged