solución Ejercicio 1 - Krayeski
PYLP-UNaM/PYLP pull request #686
Opened 2022-09-27 02:04 UTC by Maia2019

2022-09-27 12:15 UTC, martinfeldman approved these changes

2022-09-27 21:04 UTC, facurodrij requested changes
Comiteaste ademas el archivo CONTRIBUTORS.MD

2022-09-27 22:56 UTC, papazoglu approved these changes
Aprobado

2022-09-27 23:20 UTC, FacuRodriJ approved these changes
aprobado

2022-09-28 09:58 UTC, SuichiM commented
@Maia2019 fijate que tambien incluiste en este PR el archivo y commit del ejercicio anterior. recorda que para crear un nuevo ejercicio, siempre tenemos que sacar la branch de `main`

```
git checkout main // cambiarme a la branch main

git checkout -b tpX_ejX_apellido // crea una nueva branch 

// modifica el archivo

git add /path/to/the/file // se agrega el archivo para comitear

git commit -m 'fixes #nro_issue'
```

2022-09-29 14:12 UTC, SuichiM commented
![imagen](https://user-images.githubusercontent.com/21073142/193054784-6c95516d-58e1-481e-ac68-61e15942bcd2.png)

??

2022-10-10 13:21 UTC, martinlacheski approved these changes
Aprobado!

2022-10-11 11:46 UTC, merged