solución Ejercicio 4 - Rodriguez Facundo
PYLP-UNaM/PYLP pull request #742
Opened 2022-10-04 21:34 UTC by FacuRodriJ

2022-10-04 22:15 UTC, matiasagbenitez reviewed
Fíjate si podes sacar el archivo lineamientos_entrega.md del commit y dejar solo el archivo del ejercicio. Creo que podés hacerlo desde este mismo PR!

2022-10-05 13:46 UTC, FacuRodriJ commented
> Fíjate si podes sacar el archivo lineamientos_entrega.md del commit y dejar solo el archivo del ejercicio. Creo que podés hacerlo desde este mismo PR!

Listo, eliminé el archivo lineamientos_entrega.md desde el pr.

2022-10-05 15:40 UTC, matiasagbenitez approved these changes

2022-10-10 23:33 UTC, papazoglu approved these changes
Aprobado

2022-10-11 16:19 UTC, rodrigoantoniak requested changes
Esto borraría el archivo de lineamientos de entrega, debe corregirse eso.

2022-10-11 21:49 UTC, rodrigoantoniak approved these changes
Ahora si, excelente

2022-10-17 12:14 UTC, merged