solución Ejercicio 5 - Antoniak
PYLP-UNaM/PYLP pull request #747
Opened 2022-10-11 20:39 UTC by rodrigoantoniak

2022-10-13 22:34 UTC, Maia2019 approved these changes
Excelente Antoniak!

2022-10-15 00:09 UTC, matiasagbenitez approved these changes

2022-10-15 00:48 UTC, matiasagbenitez requested changes
Se aprobó solo antes. No sé qué pasó. Fijate capo que no estás usando wait y signal (la consigna lo pide)

2022-10-15 03:45 UTC, rodrigoantoniak reviewed
Corrección de ejercicio con agregado de wait y signal.

2022-10-15 03:47 UTC, matiasagbenitez approved these changes
Bien ahí! Ahora sí, `APROBADO`

2022-10-15 03:48 UTC, FacuRodriJ approved these changes
bien

2022-10-17 12:18 UTC, merged