solución Ejercicio 3 - Krayeski
PYLP-UNaM/PYLP pull request #821
Opened 2022-10-25 02:25 UTC by Maia2019

2022-10-25 02:27 UTC, matiasagbenitez approved these changes

2022-10-25 19:53 UTC, jorferr89 approved these changes
APROBADO :+1: :sunglasses:

2022-10-29 15:09 UTC, jorferr89 requested changes
Controlar el if de la línea 14... Se debería verificar si el rank==0... al ejecutar, el proceso id = 0 queda bloqueado, y el programa no finaliza su ejecución

2022-11-04 00:26 UTC, jorferr89 approved these changes
Ahora si anda bien :clap: :clap:

2022-11-08 11:21 UTC, rodrigoantoniak approved these changes
Nice

2022-11-08 11:46 UTC, merged