Solución de Ejercicio 2 - Ferreira
PYLP-UNaM/PYLP pull request #919
Opened 2022-11-15 20:03 UTC by Denisdif

2022-11-16 00:45 UTC, jorferr89 requested changes
Creo que falta el punto 3.1 planif. `static`  - 3.3 planif. `guided` - 3.4 planif. `auto`

2022-11-21 17:57 UTC, matiasagbenitez approved these changes

2022-11-21 18:32 UTC, jorferr89 approved these changes
Aprobado xq sé q se realizaron las ejecuciones con los otros planificadores

2022-11-23 00:12 UTC, Denisdif commented
@rodrigoantoniak

2022-11-23 17:14 UTC, rodrigoantoniak approved these changes

2022-11-29 20:58 UTC, merged